spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  codec:
    max-in-memory-size: 20971520
pr0gramm:
  api-client:
    url: https://pr0gramm.com/
    new-posts-url: https://pr0gramm.com/new/
    content-endpoint: api/items/get
    info-endpoint: /api/items/info
    pending-messages-endpoint: api/inbox/pending
    read-messages-endpoint: api/inbox/messages
    send-messages-endpoint: api/inbox/post
    post-comment-endpoint: api/comments/post
  image-client:
    url: https://img.pr0gramm.com/
  video-client:
    url: https://vid.pr0gramm.com/
  registration:
    enabled: false
    key-word: pr0keyrawler
  notifications:
    enabled: false
scheduler:
  enabled: true
database:
  in-memory: true
  host: localhost
  name: test
  user: sa
  password: ''
telegram:
  enabled: false
  creator-id: 12345
  username: pr0grammKeysBot
  token: test