version: "3.7"
services:
  key_crawler:
    image: "ingagnable/programmkeycrawler:latest"
    container_name: "pr0keycrawler"
    restart: always
    env_file:
      - ./config.env
    depends_on:
      - postgres_db
    links:
      - postgres_db
  postgres_db:
    image: "postgres"
    container_name: "postgres"
    restart: always
    env_file:
      - ./config.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data